### ISSUE TITLE
Can not create videos with sound

### ISSUE THREAD

**Issue by CoreyTrombley** [graphific/DeepDreamVideo#10]
From what I can tell, at no point does step 3 get a source for sound.

**Comment by ggaabe** [comment]
Hm. This makes me wonder. Google was able to get many of the images by
requesting the AI to produce what it "saw". I wonder if this same concept
can be used on audio to reproduce what the AI "hears"?

**Comment by graphific** [comment]
An experiment using recurrent neural networks is at: https://soundcloud.com/graphific/sets/rnn-against-the-machine
heavily inspired by Andrej Karpathy's work, as well as code: https://github.com/karpathy/char-rnn

**Comment by graphific** [comment]
but issue should be fixed: had still "original.mp4" hardcoded as name of movie, changed command now to:
"./3_frames2movie.sh [frames_directory] [original_video_with_sound]"

**Comment by CoreyTrombley** [comment]
i was just about to submit a PR, Sweet Thank you!

**Comment by bo01ean** [comment]
yes, had this fix in my local repo, but never PR'ed. Good stuff
