### ISSUE TITLE
No such file or directory 'mov/fear0000.jpg'

### ISSUE THREAD

**Issue by shinmai** [graphific/DeepDreamVideo#2]
There seemed to be some extra characters on line 119 of 2_dreaming_time.py. After removing those, the script seemed to run fine for one frame, but crashes with the aforementioned error.

**Comment by shinmai** [comment]
Also needed to manually create the 'frames4' and 'mov' folders.

**Comment by graphific** [comment]
yes I see: it should be fixed now, input and output dir were still hardcoded.
It will now also automatically create these directories if they don't exist.
