### ISSUE TITLE
Choosing Layers

### ISSUE THREAD

**Issue by urinieto** [graphific/DeepDreamVideo#22]
The `2_dreaming_time.py` script works fine when using the model `bvlc_googlenet.caffemodel`. However, I get the following error when I try `bvlc_reference_caffenet.caffemodel` or `finetune_flickr_style.caffemodel`:

```
Traceback (most recent call last):
  File "./2_dreaming_time.py", line 325, in <module>
    args.preview, args.octaves, args.octavescale, args.iterations, args.jitter, args.zoom, args.stepsize, args.blend, args.layers)
  File "./2_dreaming_time.py", line 188, in main
    jitter=jitter, end = endparam)
  File "./2_dreaming_time.py", line 77, in deepdream
    make_step(net, end=end, clip=clip, **step_params)
  File "./2_dreaming_time.py", line 41, in make_step
    dst = net.blobs[end]
KeyError: 'inception_4d/output'
```

I believe this happens because the `inception_4d/output` does not exist in any of these models. What type of layers are typically the most *meaningful* for humans in order to produce interesting dreamy videos? (e.g., I tried the `conv3` layer from the `finetune_flickr_style.caffemodel` but I only obtain some sort of edge detectors in the final video)

Thanks!

**Comment by graphific** [comment]
yes exactly the layers need to exist in the model.
you can print the layer names with:

’print net.blobs.types()'

the deeper the model, the more layers and choice you have: the inception models are extremely deep and therefore have the most potential to experiment with.

**Comment by urinieto** [comment]
I guess my question was not correctly framed. I meant to ask about the type of layers that produce more "interesting" dreams in terms of visualizing objects: e.g., is it better to use the ouput of a convolutional layer rather than a relu layer? which layer would you choose to visualize objects using the flickr model?

Thanks for your help!

**Comment by graphific** [comment]
investigation of different layers at http://www.csc.kth.se/~roelof/deepdream/

**Comment by urinieto** [comment]
Oh, nice! Thanks, for the info.
