### ISSUE TITLE
Motion compensation

### ISSUE THREAD

**Issue by suhr** [graphific/DeepDreamVideo#23]
Blend current frame with motion compensated difference between previous non-processed and processed frame.

**Comment by graphific** [comment]
got a pull request to work with? :)

**Comment by suhr** [comment]
Um... no. I don't have any experience with video processing.
Should I try though?

**Comment by denjello** [comment]
What about using OpticalFlow? > https://github.com/timscaffidi/ofxOpticalFlowFarneback

Might make sense as a post-producing step (between 2_ and 3_ to smooth the frames by adding respective motion blur.

**Comment by suhr** [comment]
@denjello 
The idea is that blending with more fitting result of the previous frame would improve dreaming of the current frame and might make hallucinations more stable.
Btw there's also [optical flow in OpenCV](http://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_video/py_lucas_kanade/py_lucas_kanade.html).

**Comment by graphific** [comment]
@suhr blending is already implemented:
--blend 0.5 (constant)
--blend random (random factor 0.5 - 1.0)
--blend loop (loop 0.5 <-> 1.0 and everything in betwen).

@denjello means to next to blending also keep the movement into account with optical flow. I got some code working, will try to implement it one if these days, helped by reddit: https://www.reddit.com/r/deepdream/comments/3cesna/with_optical_flow_source_in_comments/
If anyone else has time, feel free to try the code from there -^

**Comment by suhr** [comment]
@graphific I'm aware it's implemented, but consider words “more fitting”. For example, now if some head in video moves, two frames with *different* head positions are blended. With optical flow you can correct the head position before blending and dreaming.

**Comment by denjello** [comment]
@graphific > can you share a gist of what you are working on?

**Comment by graphific** [comment]
@denjello its basically just an exact copy of the reddit code, but halfway implemented, with a flag to enable it (-of, --optical_flow), so if anyone else has time: I probably wont get to it until end of the week.
