### ISSUE TITLE
2_dreaming_time.py gpu mode

### ISSUE THREAD

**Issue by lostboykev** [graphific/DeepDreamVideo#24]
I'm not saying this is an issue with your code but maybe a little insight would help me figure out what went wrong.

First thing you will notice is that I modified your code. This is because I defined gpu with --gpu 0 appended to your python script. The script runs but only using one cpu core and no gpu utilization (confirmed in nvidia-smi). In your python script 2_dreaming_time.py I changed the lines under 

 # should be picked up by caffe by default, but just in case
 # standard caffe:

to the following

    if gpu == '0':
        caffe.set_mode_gpu()
        caffe.set_device(int(args.gpu))
        print("GPU mode [device id: %s]" % args.gpu)
        print("using GPU, but you'd still better make a cup of coffee")
    else: print("SHITTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT")

if gpu (equals) 0 run this. I did this because it picked up my gpu value as 0 so it did not run originally. For some reason it picks up the 0 but doesn't utilize the gpu. And then works after it runs your commands to set the mode and device. I'm sure I have missed something hear as I'm new to caffe and python. But how is the variable gpu determined? Maybe I can find the source of my mistake. 

And thank you for your hard work. It went from 40 hours to 22 min to convert 776 frames. Can wait to put it all back together and watch!

**Comment by rosshamish** [comment]
What command exactly are you running with this modified code? What arguments are you passing on the command line?

**Comment by lostboykev** [comment]
My last run was:
 python 2_dreaming_time.py -i secondrender/ -o processed2 --model_path /home/lostboykev/caffe/models/bvlc_googlenet/ --model_name bvlc_googlenet.caffemodel --gpu 0

**Comment by graphific** [comment]
@lostboykev you know you can run 3_frames2movie.sh any time to turn the frames which are processed into a movie: it will cut out the right duration of music and put it back together with the created movie.

As for the GPU code, ill add the command for gpu you gave to the documentation. tnx!

**Comment by nikdog** [comment]
So I also had the previous version that only worked in CPU mode, and it worked, just slow. Now I've the updated one and nothing works. CPU or GPU mode.

> nikdog@Deathstar:~/Downloads/DeepDreamVideo-master$ python 2_dreaming_time.py -i '/mnt/bed3e86c-d20d-323f-bcc6-d0428a20a43e/VIDEOS/Deep_Dream/Howtocoilcables' -o '/mnt/bed3e86c-d20d-323f-bcc6-d0428a20a43e/VIDEOS/Deep_Dream/Howtocoilcables 2' --model_path ~/caffe/models/bvlc_googlenet/ --gpu 0
>  File "2_dreaming_time.py", line 164
>    else: print("SHITTTTTTTTTTTTTT You're running CPU man =D")
       ^
SyntaxError: invalid syntax
nikdog@Deathstar:~/Downloads/DeepDreamVideo-master$ python 2_dreaming_time.py -i '/mnt/bed3e86c-d20d-323f-bcc6-d0428a20a43e/VIDEOS/Deep_Dream/Howtocoilcables' -o '/mnt/bed3e86c-d20d-323f-bcc6-d0428a20a43e/VIDEOS/Deep_Dream/Howtocoilcables 2' --model_path ~/caffe/models/bvlc_googlenet/ --gpu
  File "2_dreaming_time.py", line 164
    else: print("SHITTTTTTTTTTTTTT You're running CPU man =D")
       ^
SyntaxError: invalid syntax
nikdog@Deathstar:~/Downloads/DeepDreamVideo-master$ python 2_dreaming_time.py -i '/mnt/bed3e86c-d20d-323f-bcc6-d0428a20a43e/VIDEOS/Deep_Dream/Howtocoilcables' -o '/mnt/bed3e86c-d20d-323f-bcc6-d0428a20a43e/VIDEOS/Deep_Dream/Howtocoilcables 2' --gpu
  File "2_dreaming_time.py", line 164
    else: print("SHITTTTTTTTTTTTTT You're running CPU man =D")
       ^
SyntaxError: invalid syntax
nikdog@Deathstar:~/Downloads/DeepDreamVideo-master$ python 2_dreaming_time.py -i '/mnt/bed3e86c-d20d-323f-bcc6-d0428a20a43e/VIDEOS/Deep_Dream/Howtocoilcables' -o '/mnt/bed3e86c-d20d-323f-bcc6-d0428a20a43e/VIDEOS/Deep_Dream/Howtocoilcables 2' --gpu 0
  File "2_dreaming_time.py", line 164
    else: print("SHITTTTTTTTTTTTTT You're running CPU man =D")
       ^
SyntaxError: invalid syntax
nikdog@Deathstar:~/Downloads/DeepDreamVideo-master$ python 2_dreaming_time.py -i '/mnt/bed3e86c-d20d-323f-bcc6-d0428a20a43e/VIDEOS/Deep_Dream/Howtocoilcables' -o '/mnt/bed3e86c-d20d-323f-bcc6-d0428a20a43e/VIDEOS/Deep_Dream/Howtocoilcables 2'
  File "2_dreaming_time.py", line 164
    else: print("SHITTTTTTTTTTTTTT You're running CPU man =D")
       ^
SyntaxError: invalid syntax

**Comment by graphific** [comment]
@nikdog small indentation error, fixed now

**Comment by lostboykev** [comment]
@graphific Thanks for using my fix! And I have used the third script. Works like a charm. My videos though don't blend well. It looks like the models are just overlayed on top with small alterations through out. Not sure what that is about if you have any insight in that.

**Comment by rosshamish** [comment]
@lostboykev Might want to look into a variable/rolling blend factor, as @graphific [described in pseudocode](https://github.com/graphific/DeepDreamVideo/issues/25#issuecomment-120234121) in issue #25. 

I don't want to speak for @graphific but if you get it working, it's probably worth a pull request as a new command line argument
