### ISSUE TITLE
Question about alpha / mix

### ISSUE THREAD

**Issue by jbum** [graphific/DeepDreamVideo#25]
In your readme, you say "every next unprocessed frame in the movie clip is blended with the previous processed frame before being "dreamed" on, moving the alpha from 0.5 to 1 and back again".  Looking at the code, it looks like you are using a fixed mix amount ( which defaults to 0.5) and not fluctuating it, as described.  Your video appears to be using a different mix amount than 0.5 (e.g. less of the previous frame) - it looks closer to what I see if I use .25/.75.  Could you clarify?

**Comment by rosshamish** [comment]
For reference:

[blend passed as argument](https://github.com/graphific/DeepDreamVideo/blob/master/2_dreaming_time.py#L289)
```python
    parser.add_argument(
        '-b','--blend', 
        type=float, 
        required=False,
        help='Blend Amount. Default: 0.5')

```

it gets passed into main, and is used [when calling morphPicture](https://github.com/graphific/DeepDreamVideo/blob/master/2_dreaming_time.py#L216)
```python
        if blend == 0:
            newimg = PIL.Image.open(newframe)
            if preview is not 0:
                newimg = resizePicture(newframe,preview)
            frame = newimg
        else:
            frame = morphPicture(saveframe,newframe,blend,preview)
```

[morphPicture](https://github.com/graphific/DeepDreamVideo/blob/master/2_dreaming_time.py#L101)
```python
def morphPicture(filename1,filename2,blend,width):
	img1 = PIL.Image.open(filename1)
	img2 = PIL.Image.open(filename2)
	if width is not 0:
		img2 = resizePicture(filename2,width)
	return PIL.Image.blend(img1, img2, blend)
```

**Comment by jbum** [comment]
Yes, I saw that.  My understanding of what you wrote was that the blend value was changing dynamically from frame to frame.  I guess that's not what you meant.

**Comment by rosshamish** [comment]
Sorry for the confusion - I'm not the author, my comment was intended to make it easier for the author to answer.

**Comment by jbum** [comment]
Ah, gotcha - thanks.

**Comment by graphific** [comment]
@rosshamish thanks for the expanations, appreciate it, and correct :)

@jbum: yes for the Fear and Loathing in Las Vegas I had a moving blending factor, so basically just an array to loop through. In its most simple form:

```python
blend = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 0.9, 0.8, 0.7, 0.6, 0.5]
for i in frame:
    do stuff()
    morphPicture(img1,img2,blend[iterator]
    reset_iterator() if at last index of blend
```

**Comment by jbum** [comment]
Okay - I suspected as much - thank you!
