### ISSUE TITLE
Syntax error in 2_dreaming_time.py

### ISSUE THREAD

**Issue by eighteight** [graphific/DeepDreamVideo#3]
After successfully running the first script and having extracted the frames from a video, I then get this error:

$eight: DeepDreamVideo: ./2_dreaming_time.py -i frames -o processed
  File "./2_dreaming_time.py", line 136
    end=layersloop[frame_i % len(layersloop)],iter_n = 5) ])
                                                          ^
SyntaxError: invalid syntax
$eight: DeepDreamVideo:

**Comment by graphific** [comment]
k depends on cutoff I guess of editor, fixed now.

**Comment by eighteight** [comment]
Now I get 

$eight: DeepDreamVideo: ./2_dreaming_time.py -i frames -o processed
  File "./2_dreaming_time.py", line 135
    frame = deepdream(net, frame, end=layersloop[frame_i % len(layersloop)],iter_n = 5) ])
                                                                                        ^
SyntaxError: invalid syntax
$eight: DeepDreamVideo:

**Comment by graphific** [comment]
should be fixed now, ran it myself again and all working for me at least...

**Comment by eighteight** [comment]
Thanks. That error ran away, but now it misses the PIL.Image library:

$eight: DeepDreamVideo: ./2_dreaming_time.py -i frames -o processed
Traceback (most recent call last):
  File "./2_dreaming_time.py", line 12, in <module>
    import PIL.Image
ImportError: No module named PIL.Image
$eight: DeepDreamVideo: 


I do have Pillow installed
$eight: DeepDreamVideo: pip freeze
backports.ssl-match-hostname==3.4.0.2
certifi==2015.4.28
decorator==3.4.2
Django==1.8.2
futures==2.2.0
gnureadline==6.3.3
image==1.4.0
ipython==3.1.0
Jinja2==2.7.3
jsonschema==2.4.0
livestreamer==1.12.2
MarkupSafe==0.23
matplotlib==1.4.3
mercurial==2.5.1.post20130210
mock==1.0.1
networkx==1.9.1
nose==1.3.4
numpy==1.9.1
pandas==0.16.1
Pillow==2.9.0
pylab==0.1.3
pyparsing==2.0.3
python-dateutil==2.4.2
pytz==2015.4
pyzmq==14.6.0
requests==2.6.0
RL-Glue-PythonCodec==2.2
scikit-image==0.11.3
scikit-learn==0.16.1
scipy==0.15.1
seaborn==0.5.1
singledispatch==3.4.0.3
six==1.8.0
sympy==0.7.6
tornado==4.1
tsp-solver==0.1
VTK==5.10.1
wheel==0.24.0
$eight: DeepDreamVideo: 

Is there anything else I should install? 

Thanks.

**Comment by graphific** [comment]
maybe try pip install Image?

**Comment by eighteight** [comment]
That had been installed already:

$eight: pip install Image
Requirement already satisfied (use --upgrade to upgrade): Image in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pillow in /usr/local/lib/python2.7/site-packages (from Image)
Requirement already satisfied (use --upgrade to upgrade): django in /usr/local/lib/python2.7/site-packages (from Image)
$eight: xcode:
