### ISSUE TITLE
Blend examples "Not Found"

### ISSUE THREAD

**Issue by Ubiquitous** [graphific/DeepDreamVideo#32]
FYI: Examples (eg. [blend1](https://camo.githubusercontent.com/e893b558ea9614d9b400b4e4c7d7438c774ab3d4/687474703a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f456476347941364d496a707a445032772f67697068792e676966), blend2, blend3) under "Blending Options" in the [readme.md](https://github.com/graphific/DeepDreamVideo/blob/master/README.md) are broken.

Nice looking tool
~ cheers!

**Comment by graphific** [comment]
yeh somehow didnt want to take external sources, so uploaded the gifs to the repo, readme fixed, possibly bad point: 3 gifs together = 40mb extra to download.
