### ISSUE TITLE
New Build Returns Error

### ISSUE THREAD

**Issue by reillydonovan** [graphific/DeepDreamVideo#36]
I have everything working on the previous build, got the most recent build and terminal returned the following:

  File "2_dreaming_time.py", line 492, in <module>
    main(args.input, args.output, args.image_type, args.gpu, args.model_path, args.model_name, args.preview, args.octaves, args.octavescale, args.iterations, args.jitter, args.zoom, args.stepsize, args.blend, args.layers, args.guide_image, args.start_frame, args.end_frame, args.verbose)
  File "2_dreaming_time.py", line 328, in main
    frame = deepdream(net, frame, image_type=image_type, verbose=verbose, iter_n = iterations, step_size = stepsize, octave_n = octaves, octave_scale = octave_scale, jitter=jitter, end = endparam)
  File "2_dreaming_time.py", line 139, in deepdream
    showarray(vis)
  File "2_dreaming_time.py", line 28, in showarray
    display(Image(data=f.getvalue()))
NameError: global name 'display' is not defined
any idea what's causing the problemo?

**Comment by graphific** [comment]
you're sure you're using the newest version, as the most recent version has display(Image(data=f.getvalue())) on line 24 and 30, not line 28 for instance.
also are you running it in a terminal, then make sure you set --verbose to 1 or 2, not 3

**Comment by reillydonovan** [comment]
It is the latest build the line numbers are returning different values because I had to add a system path directory for my caffe library...  the test that I reported I ran verbose at 3... other tests I've done say that it is processing the frame but it never starts... I'll try again and report back!

**Comment by reillydonovan** [comment]
Does it still print its progress with each deep dream pass to console or will it now only report when it is done with a frame?

**Comment by reillydonovan** [comment]
It does work, it was the -v 3.  Also, I was expecting it to print to terminal its progress with each frame, which is does not seem to do anymore (or perhaps there is a command for this), so I patiently waited for a processed image to appear, which it did :).

**Comment by graphific** [comment]
if you want to print the progress, its -v 1, if also the layers -v 2, if also pictures (display) -v 3
