### ISSUE TITLE
Blend seems to be broken

### ISSUE THREAD

**Issue by lazerozen** [graphific/DeepDreamVideo#42]
Hey there,
great stuff! Thanks a lot for making this!

The -b parameter seems to be broken. No matter, what I enter (0, 0.0, 1, 1.0) - I always get "float is expected". Loop works and omitting the parameter works (and gives 0.5 I'd say).

**Comment by graphific** [comment]
strange, the code clearly states its a string, are you sure you've pulled the latest version?
<pre>
parser.add_argument(
        '-b','--blend',
        type=str,
        required=False,
        help='Blend Amount. Default: "0.5" (constant), or "loop" (0.5-1.0), or "random"')</pre>

**Comment by lazerozen** [comment]
Yes, I have latest. And the argument is defined as in your snippet. Did you try entering a value on your machine=

**Comment by graphific** [comment]
yes I see the problem: giving a float as argument, it was picked up as string, but not casted back to float.
fixed now, tnx for the issue report.

**Comment by lazerozen** [comment]
yay!
