### ISSUE TITLE
How to use other model

### ISSUE THREAD

**Issue by JuanWilde** [graphific/DeepDreamVideo#44]
Hi! I tried to use other model lib but I have an error with de layerloop array:

layersloop = ['inception_4c/output', 'inception_4d/output',
              'inception_4e/output', 'inception_5a/output',
              'inception_5b/output', 'inception_5a/output',
              'inception_4e/output', 'inception_4d/output',
              'inception_4c/output']

Any idea? Thanks

**Comment by jimbrayton** [comment]
What was the error message?

**Comment by graphific** [comment]
@JuanWilde the layers have to exist in the neural network (model) you're loading, you can print the layers with net.blobs.keys(). The layers above will only work for the GoogLeNet models. An overview of models and layers + visualiation can also be seen at: http://www.csc.kth.se/~roelof/deepdream/ ->
- VIS_bvlc_googlenet_allLayers
- VIS_googlenet_places205_allLayers
- VIS_finetune_flickr_style_allLayers
- VIS_alexnet_places_allLayers
- VIS_oxford102flowers_allLayers

**Comment by JuanWilde** [comment]
Yep, that was I thought after getting the error. I'll check your link to test other models, because with the googlenet I only have birds, eyes, and other rare animals... :S

https://youtu.be/VnigsXyKbTo

Best, Juan.
