### ISSUE TITLE
out of GPU memory

### ISSUE THREAD

**Issue by primordialTruth** [graphific/DeepDreamVideo#46]
When trying to process large quantities of large frames (1080 or 720 video extracts) I quickly run out of GPU space. I have tried this on both amazon GPU instances (4GB and 8GB nvidia cards if i recall correctly) and they both produce similar results. this is not entirely unexpected, as its a lot of info being processed, but i was wondering what i could do to ameliorate this? my attempts have included: CPU (works, if you want to spend a week processing), the aforementioned amazon instances, changing the prototxt batch_size parameters to 1 (read it somewhere, not sure of it's efficacy).

any thoughts would be appreciated; i am happy to hack away at any suggestions on my own and provide any code in the unlikely event i make progress. 

thanks for the cool tool!

using: nvidia gtx960 2gb, caffe with the default imageset used by DDV, openblas

Error:
F0720 12:01:17.580993 21406 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

**Comment by wrenchpilot** [comment]
I was able to squeeze a little bit more out of the GPU memory by applying this patch to caffe:
https://github.com/BVLC/caffe/commit/1dcfc3ce220f4fa80e27ffdd7cc0b3223c84c75e

" share columnation buffers for convolution to save memory

share the im2col / col2im buffers among convolution + deconvolution
layers by making the buffer a static member."

**Comment by primordialTruth** [comment]
jeeze that was fast, let a guy sip his coffee! but thanks, i'll look in to it

**Comment by primordialTruth** [comment]
i put in the relevant changes and recompiled, and now it renders 720 swimmingly! 1080 still kills it-- if there are any other suggestions, i'd love to hear them, otherwise i'll just make do with 720. regardless, thank you wrench, you saved my CPU several days of hassle.

**Comment by primordialTruth** [comment]
further
