### ISSUE TITLE
Fix for paths with spaces (Windows)

### ISSUE THREAD

**Issue by projectgheist** [graphific/DeepDreamVideo#48]
This is concerning the 1_movie2frames.sh file.

My environment variable for ffmpeg has a space in it and results in an error with "Can't find [folder] ...".
This is fixed by adding quotes around the ffmpeg variable when executing (all the other parameters seem to have it).

From
```
$FFMPEG -i "$2" -f image2 "${OUTFILES}"
```
To
```
"$FFMPEG" -i "$2" -f image2 "${OUTFILES}"
```

This should presumably also be done for: $AVCONV and $MPLAYER

**Comment by denjello** [comment]
you're absolutely right. i'll include that in the shell script rewrite that I am working on.

**Comment by graphific** [comment]
@projectgheist tnx for the issue report, should be fixed now.
