### ISSUE TITLE
No such functions: 'display' and 'clear_output'

### ISSUE THREAD

**Issue by ashmanov** [graphific/DeepDreamVideo#5]
Hi, 
I'm trying to launch 2_dreaming_time.py, but it fails at the line "display(Image(data=f.getvalue()))". There is no function named display.
When I remove that line, it fails at the line "clear_output(wait=True)", because there is no such function "clear_output".
What should I do?

**Comment by graphific** [comment]
yes if you run it from terminal without external display (remote server?) or instead of ipython notebook where I ran it from, you wont be able to display the processed frames, so you can uncomment those lines. I'll add a --display option
