### ISSUE TITLE
SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by JacksonGariety** [graphific/DeepDreamVideo#51]
I get a segmentation fault when using the OpenCL fork of caffe with DeepDreamVideo:

https://github.com/BVLC/caffe/pull/2610

Anyone run into this before? Any idea where to start debugging?

**Comment by naibaf7** [comment]
@JacksonGariety 
Should be fixed with:
https://github.com/naibaf7/caffe/commit/2806b26006f66a92916427c35cd2710fcad08a6f
mind to try again?

**Comment by JacksonGariety** [comment]
Still segfaults at the same place:

    caffe::DeviceContext::num_queues() + 9

**Comment by naibaf7** [comment]
Ok that is weird, because I am fairly certain it stems from having no valid DeviceContext loaded when starting the network.
As python proxies over SetDevice, this should essentially fix the problem. At least it did for me.

**Comment by JacksonGariety** [comment]
@naibaf7 I pulled, completely deleted the build directory and then re-ran cmake. It checked the git log and it includes your fix. I also moved the `caffe/python` directory to see if DeepDream would respond with `no module named caffe` which was the case.

**Comment by JacksonGariety** [comment]
@naibaf7 have you looked at this? Seems like the same error: http://stackoverflow.com/questions/17148978/opencl-segmentation-fault-while-accessing-device-info

**Comment by naibaf7** [comment]
No, now it could actually be an issue with the python code.

See, this code:
```
    if gpu is None:
        print("SHITTTTTTTTTTTTTT You're running CPU man =D")
    else:
        caffe.set_mode_gpu()
        caffe.set_device(int(args.gpu))
        print("GPU mode [device id: %s]" % args.gpu)
        print("using GPU, but you'd still better make a cup of coffee")
```

gets called after

```
    # Patching model to be able to compute gradients.
    # Note that you can also manually add "force_backward: true" line to "deploy.prototxt".
    model = caffe.io.caffe_pb2.NetParameter()
    text_format.Merge(open(net_fn).read(), model)
    model.force_backward = True
    open('tmp.prototxt', 'w').write(str(model))

    net = caffe.Classifier('tmp.prototxt', param_fn,
                           mean = np.float32([104.0, 116.0, 122.0]), # ImageNet mean, training set dependent
                           channel_swap = (2,1,0)) # the reference model has channels in BGR order instead of RGB
```

in the file ```https://github.com/graphific/DeepDreamVideo/blob/master/2_dreaming_time.py```.
This means when the network is instantiated, it does not load a valid DeviceContext from OpenCL because none exists at that point. As soon as the network is then Reshaped, it fails.
Maybe it is already enough to swap those two code blocks (I hope so). Otherwise, more work is required.

**Comment by JacksonGariety** [comment]
@naibaf7 Your PR fixes the segfault for me, thank you!

Can you shed some light on how to run CPU + GPU at the same time to get 1.7x speed boost?

**Comment by naibaf7** [comment]
You're welcome ;)

Well that depends on what you want to process. It would be easiest to run two instances (one with each gpu=0 and gpu=1) of the code on different images / videos.

If you want to process one video with continuous "image dreaming", this is currently not really possible and would depend on future multi-GPU approaches that are being developed for Caffe right now.

**Comment by JacksonGariety** [comment]
@naibaf7 ah, I had a feeling that'd be the case. It does loop after an exact # of frames (starting the neural network over, I believe), so I could potentially cut the vid in half and run half of them on GPU and half on CPU.

**Comment by JacksonGariety** [comment]
@naibaf7 again, thanks for all your help!

**Comment by graphific** [comment]
tnx @naibaf7
