### ISSUE TITLE
Runtime error in 2_dreaming_time.py script: "KeyError: 'inception_4d/output'"

### ISSUE THREAD

**Issue by 4science** [graphific/DeepDreamVideo#53]
Getting a runtime error while running 2_dreaming_time.py using the places205CNN_iter_upgraded.caffemodel

The model seems to load up fine as it says Processing frame #1 before the errors start to show:

I0901 23:34:43.718667  5753 upgrade_proto.cpp:618] Attempting to upgrade input file specified using deprecated V1LayerParameter: /home/alex/Code/caffe/models/places205/places205CNN_iter_300000_upgraded.caffemodel
I0901 23:34:43.886610  5753 upgrade_proto.cpp:626] Successfully upgraded file specified using deprecated V1LayerParameter
Processing frame #1
Setting up Guide with selected image
Traceback (most recent call last):
  File "2_dreaming_time.py", line 506, in <module>
    main(args.input, args.output, args.image_type, args.gpu, args.model_path, args.model_name, args.preview, args.octaves, args.octavescale, args.iterations, args.jitter, args.zoom, args.stepsize, args.blend, args.layers, args.guide_image, args.start_frame, args.end_frame, args.verbose)
  File "2_dreaming_time.py", line 335, in main
    guide_features = prepare_guide(net,PIL.Image.open(guide_image), end=endparam)
  File "2_dreaming_time.py", line 77, in prepare_guide
    (src, dst) = (net.blobs["data"], net.blobs[end])
KeyError: 'inception_4d/output'

**Comment by graphific** [comment]
KeyError: 'inception_4d/output' implies that the model you're using doesnt have that particulat layer. you can print out the layers with _print net.blobs_
