### ISSUE TITLE
Unexpected result

### ISSUE THREAD

**Issue by martync** [graphific/DeepDreamVideo#62]
Hi, 
I'm currently trying your command line and after a small fight with anaconda/numpy/caffe I finally have things working. 

The command `2_dreaming_time.py`asked for model_path and model_name so I gave him those args : 
`python 2_dreaming_time.py -i inputfolder -o outputfolder -l inception_5b/output -it jpg --model_path /Users/(...)/Downloads/caffe-master/models/bvlc_googlenet --model_name bvlc_reference_caffenet.caffemodel`

And here is the result : 
![00000001](https://cloud.githubusercontent.com/assets/240125/16896825/94564f34-4b9f-11e6-8e93-3ecb8b1c8359.jpg)
I was expecting a bit more. 

Everything in your Readme seems easy, is there anything I'm doing wrong ? do I have to play with different layers and coffemodel ?

Thanks

**Comment by graphific** [comment]
for a stronger result you can change the number of iterations from the default 10 to a higher number 

`-itr 100`

more parameters are possible to tweak, see the readme for examples: for instance the jitter, stepsize, octaves, etc. Good luck!
