### ISSUE TITLE
Error when I try to run 2_dreaming_time.py

### ISSUE THREAD

**Issue by JodiCode** [graphific/DeepDreamVideo#63]
`E1213 07:37:28.288794  4352 upgrade_proto.cpp:618] Attempting to upgrade input file specified using deprecated V1LayerParameter: ../caffe/models/bvlc_googlenet/bvlc_googlenet.caffemodel
I1213 07:37:28.344841  4352 upgrade_proto.cpp:626] Successfully upgraded file specified using deprecated V1LayerParameter
Processing frame #1
C:\.dev\Anaconda27\lib\site-packages\scipy\ndimage\interpolation.py:568: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
C:\.dev\Anaconda27\lib\site-packages\scipy\ndimage\interpolation.py:571: RuntimeWarning: divide by zero encountered in true_divide
  zoom = (numpy.array(input.shape) - 1) / zoom_div
C:\.dev\Anaconda27\lib\site-packages\scipy\ndimage\interpolation.py:571: RuntimeWarning: invalid value encountered in true_divide
  zoom = (numpy.array(input.shape) - 1) / zoom_div`

This is printed to Anaconda any time I try to run dreaming time with any flags other than -i -o and -it
I can run the script normally.

Any help would be appreciated, thanks

**Comment by graphific** [comment]
what is the exact command you're trying to run, so python 2_dreaming_time.py ...

**Comment by JodiCode** [comment]
so for example I would do `python 2_dreaming_time.py -i frame_dir -o frame2_dir -it jpg --gpu 0` and it would work fine.
But if I add anymore arguments to the command it gives me the error above:
e.g. `python 2_dreaming_time.py -i frame_dir -o frame2_dir -it jpg --gpu 0 -oct 20 -octs 2.0 -itr 50`

**Comment by JodiCode** [comment]
Update: This error seems to have fixed itself, I have no idea how it's fixed but i'm not getting errors anymore.
Sorry for not being able to provide any info, it seems that a restart or two was required though.
